### ISSUE TITLE
Build-Lock after AI lost the Paragon

### ISSUE THREAD

**Issue by daLocu** [Uveso/AI-Uveso#1]
If AI-Uveso has finished Paragon many construction projects starts. But these projects doesn't canceled after the Paragon gets destroyed.

**Comment by Uveso** [comment]
Yeah, i know. :/
Assisting engineers will be set on pause on low eco, but not the initial builder.

I am testing some functions that will pause the initial builder and also pause factories on low eco.
Will be part of the next update. (v68)

**Comment by Uveso** [comment]
fixed

**Comment by daLocu** [comment]
Hi Uveso, 

we had time to test v68 yesterday.  


First of all, we are very excited about your work and find the AI ​​really awesome.  

Therefore, your AI is close to our hearts and we would like to tell you the following: 

- AI has placed the Paragon very centrally in its base.
- After an air raid by us the AI ​​did not recover. 
- When our ground forces arrived, the base was barely rebuilt and many unfinished experiments were still in base.  

Our ideas are: 

(1) AI with Paragon should not build so much experimentals parallelized.  

(2) AI should build the Paragon off the base.  

(3) improved protection of the paragon by T3 air defense and earlier counterattack with air forces. 

(4) After losing the Paragon AI should reclaim the started and non-finished experimentals to gain mass.

Of course, we can not say whether these suggestions are technically feasible and whether the required effort is appropriate.  

best regards

**Comment by Uveso** [comment]
1. Well, this is one of the main features that my AI can build several
experimentals at the same time.
This is because i can't assign more then 20 engineers to assist an
experimental. More engineers will get stucked and can't move then.


2. There is no way to tell the AI where it has to build a new building.
It will always use the first free space from the center of the base.
This is a c-engine function and can't be changed from LUA side.

3. Adding some T3AA to protect a paragon is a good idea and i will add it.

4. Reclaiming unfinished experimentals if no paragon is left is also a good idea.
I will add that too.
